<a href="https://colab.research.google.com/github/Ayantika1998/Assignments/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing Numpy**

In [2]:
import numpy as np #importing library

### Exercise

* Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

* Generate a matrix (2D numpy array) of the values:

\begin{align}
  \mathbf{A} =
  \begin{pmatrix}
    1 & 2 & 4 \\
    2 & 3 & 0 \\
    0 & 5 & 1
  \end{pmatrix}
\end{align}

* Change the dimensions of this array to another permitted shape

## **Generating a 1D Array**

In [11]:
oneD_list = [7, 9, 65, 33, 85, 99]

In [14]:
oneD_array = np.array(oneD_list)
print(type(oneD_array))
print(oneD_array)

<class 'numpy.ndarray'>
[ 7  9 65 33 85 99]


## **Generating a 2D Array**

In [15]:
oneD_list_1 = [1,2,4]
oneD_list_2 = [2,3,0]
oneD_list_3 = [0,5,1]

In [16]:
TwoD_array = np.array([oneD_list_1, oneD_list_2,oneD_list_3])
print("TwoD_array:\t" , TwoD_array)
print("Size:\t" , TwoD_array.size)
print("Shape:\t", TwoD_array.shape)

TwoD_array:	 [[1 2 4]
 [2 3 0]
 [0 5 1]]
Size:	 9
Shape:	 (3, 3)


## **Reshaping 2D Array**

In [18]:
#3*3=9*1
TwoD_array = TwoD_array.reshape(9,1)
print("TwoD_array:\t" , TwoD_array)
print("size:\t" , TwoD_array.size)
print("shape:\t", TwoD_array.shape)

TwoD_array:	 [[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]]
size:	 9
shape:	 (9, 1)


### Exercise

* #### Create an array of string numbers, but use dtype to make it an array of floats.
* #### Transpose the matrix, printing the new size and shape.
* #### Use the .astype() method to convert the array to boolean.

## **Array of string numbers of dtype floats**

In [46]:
string_array = np.array(['10','20','30','40'], dtype='float64')

## **Transposing the matrix and printing the new size and shape**

In [47]:
TwoD_array.shape = (3, 3)
print(TwoD_array, "\n")
print(TwoD_array.T)

[[1 2 4]
 [2 3 0]
 [0 5 1]] 

[[1 2 0]
 [2 3 5]
 [4 0 1]]


## **Two change Dtype**

In [51]:
print(type(string_array))
print(string_array.astype('bool'))

<class 'numpy.ndarray'>
[ True  True  True  True]


### Exercise

* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2 $\pi$ in steps of 0.1

For one of the arrays generated:
* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

In [63]:
zero_Array = np.zeros(50)
print(zero_Array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [64]:
twos_Array = np.repeat(2, 20)
print(twos_Array)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [67]:
import math
array_2pi = np.arange(0,2*(math.pi),0.1)
array_2pi

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [69]:
array_2pi[:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

In [71]:
array_2pi[-3]

6.0

In [72]:
array_2pi[4:8]

array([0.4, 0.5, 0.6, 0.7])

### Exercise
Take one of the arrays you defined and
* #### Reverse it
* #### Only keep every 4th element.
* #### Get every 2nd element, starting from the last and moving backwards.

In [76]:
np.flip(string_array)

array([40., 30., 20., 10.])

In [77]:
string_array[0::4]

array([10.])

In [81]:
string_array[::-2]

array([40., 20.])

### Exercise

* Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [84]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


### Exercise
* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
* Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.


In [88]:
roll = np.random.choice(list(range(1,4)),10)
roll

array([1, 1, 3, 1, 1, 1, 2, 3, 2, 3])

In [89]:
np.random.choice(["H","H","T"],10)

array(['H', 'H', 'T', 'H', 'H', 'H', 'T', 'H', 'H', 'H'], dtype='<U1')